// Cinematic takedown library. Each step: t (seconds), b = batman pose, v = victim pose,
// vp = victim placement {f: distance in front of batman, y: height, ry: extra yaw}, hit/crack flags, fx(ctx).
import { POSES } from './character.js';

const P = (base, extra) => ({ ...POSES[base], ...extra });
const jab = (b = 'punchL', v = 'hurt', t = 0.26) => ({ t, b, v, vp: { f: 1.15 }, hit: 1 });

export const KILLS = [
  { name: 'HEAD REMOVAL', steps: [jab('punchL'), jab('punchR'),
    { t: 0.5, b: 'grab', v: 'choke', vp: { f: 0.8, y: 0.15 }, fx: (c) => c.sfx('scream', { vol: 0.7 }) },
    { t: 0.35, b: 'twist', v: P('choke', { hdy: 1.2 }), vp: { f: 0.8, y: 0.2 }, crack: 1 },
    { t: 0.4, b: 'lift', v: P('choke', { hdy: -1.2 }), vp: { f: 0.8, y: 0.25 }, crack: 1 }],
    end: (c) => c.kill('decap', 1, { headForce: 1.6 }) },
  { name: 'NECK SNAP 360', steps: [jab('punchR'),
    { t: 0.45, b: 'grab', v: 'choke', vp: { f: 0.85, y: 0.05 } },
    { t: 0.5, b: 'twist', v: P('choke', { hdy: 3.14 }), vp: { f: 0.85, y: 0.05 }, crack: 2, fx: (c) => c.g.spray(c.head(), c.up, 20, 2, 0.6) }],
    end: (c) => c.kill('snap') },
  { name: 'PILEDRIVER', steps: [jab('punchL'),
    { t: 0.5, b: 'lift', v: 'heldhigh', vp: { f: 0.3, y: 0.8 } },
    { t: 0.35, b: 'crouch', v: P('heldhigh', { hx: -3.1, hy: 1.1 }), vp: { f: 0.6, y: 0.4 } },
    { t: 0.12, b: 'crouch', v: P('heldhigh', { hx: -3.1, hy: 0.4 }), vp: { f: 0.6, y: 0 }, crack: 2, fx: (c) => { c.g.shockwave(c.n.pos, 4); c.shake(0.8); } }],
    end: (c) => c.kill('crush') },
  { name: 'UPPERCUT INTO ORBIT', steps: [jab('punchL'), jab('punchR'),
    { t: 0.35, b: 'crouch', v: 'hurt', vp: { f: 1.1 } },
    { t: 0.9, b: 'uppercut', v: 'heldhigh', vp: { f: 1.3, y: 14, spd: 2.2 }, hit: 1, fx: (c) => { c.slow(0.5); c.sfx('whoosh', { rate: 0.6 }); } }],
    end: (c) => c.kill('gib', 2.6, { sky: true }) },
  { name: 'THE WISHBONE', steps: [jab('punchR'),
    { t: 0.5, b: 'lift', v: P('heldhigh', { lz: -1.2, rz: 1.2 }), vp: { f: 0.4, y: 0.9 } },
    { t: 0.5, b: 'slam', v: P('heldhigh', { lz: -1.6, rz: 1.6 }), vp: { f: 0.4, y: 1 }, crack: 1, fx: (c) => c.sfx('scream', { vol: 0.8, rate: 1.2 }) }],
    end: (c) => c.kill('halve') },
  { name: 'LIMB HARVEST', steps: [jab('punchL'), jab('punchR'),
    { t: 0.4, b: 'grab', v: 'hurt', vp: { f: 0.9 }, fx: (c) => c.g.dismember(c.n.ch, ['armL'], c.side.clone().multiplyScalar(-6)) },
    { t: 0.4, b: 'twist', v: 'hurt', vp: { f: 0.9 }, fx: (c) => { c.g.dismember(c.n.ch, ['armR'], c.side.clone().multiplyScalar(6)); c.sfx('scream', { vol: 0.9 }); } },
    { t: 0.4, b: 'kick', v: 'kneel', vp: { f: 1 }, fx: (c) => c.g.dismember(c.n.ch, ['legL'], c.dir.clone().multiplyScalar(6)) }],
    end: (c) => { c.g.dismember(c.n.ch, ['legR'], c.dir.clone().multiplyScalar(7)); c.kill('corpse'); } },
  { name: 'CURB EXECUTION', steps: [jab('punchL'),
    { t: 0.4, b: 'slam', v: 'facedown', vp: { f: 1.1 }, crack: 1, fx: (c) => c.g.teeth(c.head(), c.up, 5) },
    { t: 0.4, b: 'stomp', v: 'facedown', vp: { f: 0.75 } }],
    end: (c) => c.kill('headsplode') },
  { name: 'SPIN KICK DECAPITATION', steps: [jab('punchR'),
    { t: 0.3, b: 'crouch', v: 'hurt', vp: { f: 1.4 } },
    { t: 0.25, b: 'spin', v: 'hurt', vp: { f: 1.4 }, fx: (c) => c.sfx('whoosh', { rate: 0.8, vol: 0.8 }) }],
    end: (c) => { c.slow(0.8); c.kill('decap', 1, { headForce: 3 }); } },
  { name: 'ELECTRIC FUNERAL', steps: [jab('punchL'),
    { t: 1.6, b: 'grab', v: 'shock', vp: { f: 0.9 }, fx: (c) => { c.g.arcs(c.n.ch, 1.6); c.sfx('scream', { vol: 1 }); c.n.ch.tint('#000', 0); c.charTo(1.5); } }],
    end: (c) => c.kill('ash') },
  { name: 'CAPE CHOKE', steps: [
    { t: 0.4, b: 'grab', v: 'hurt', vp: { f: 0.8 } },
    { t: 2.0, b: 'lift', v: 'choke', vp: { f: 0.7, y: 0.6 }, fx: (c) => c.tintTo('#5a2a7a', 2) }],
    end: (c) => c.kill('corpse', 1, { purple: 1 }) },
  { name: 'HEART PUNCH', steps: [jab('punchL'), jab('punchR'),
    { t: 0.2, b: 'crouch', v: 'hurt', vp: { f: 1.0 } },
    { t: 0.6, b: 'punchR', v: P('hurt', { sp: -0.3, hdx: -0.4 }), vp: { f: 1.0 }, hit: 2, fx: (c) => { c.slow(0.6); c.heart(); } }],
    end: (c) => c.kill('corpse') },
  { name: 'BODY SLAM', steps: [jab('punchL'),
    { t: 0.6, b: 'lift', v: 'heldhigh', vp: { f: 0.3, y: 1 } },
    { t: 0.15, b: 'slam', v: 'heldhigh', vp: { f: 1.6, y: 0.1, spd: 20 }, crack: 2, fx: (c) => { c.g.shockwave(c.n.pos, 6); c.shake(1); } }],
    end: (c) => c.kill('gib', 1.8) },
  { name: 'BAT-ERANG SHREDDER', steps: [
    { t: 0.18, b: 'throw', v: 'hurt', vp: { f: 2.2 }, hit: 1 }, { t: 0.18, b: 'aim', v: 'hurt', vp: { f: 2.3 }, hit: 1 },
    { t: 0.18, b: 'throw', v: 'hurt', vp: { f: 2.4 }, hit: 1, fx: (c) => c.g.dismember(c.n.ch, ['armL'], c.dir.clone().multiplyScalar(5)) },
    { t: 0.18, b: 'aim', v: 'hurt', vp: { f: 2.5 }, hit: 1, fx: (c) => c.g.dismember(c.n.ch, ['armR'], c.dir.clone().multiplyScalar(5)) }],
    end: (c) => c.kill('decap', 1, { headForce: 2 }) },
  { name: 'FLOOR TO CEILING', steps: [jab('punchR'),
    { t: 0.3, b: 'grab', v: 'held', vp: { f: 0.8, y: 0.3 } },
    { t: 0.2, b: 'slam', v: 'facedown', vp: { f: 1.2 }, crack: 1, fx: (c) => c.g.pool(c.n.pos.x, c.n.pos.z, 1) },
    { t: 0.3, b: 'lift', v: 'heldhigh', vp: { f: 0.6, y: 1.2, spd: 14 } },
    { t: 0.2, b: 'slam', v: 'facedown', vp: { f: 1.2, spd: 20 }, crack: 1, fx: (c) => { c.g.pool(c.n.pos.x, c.n.pos.z, 1.5); c.g.teeth(c.head(), c.up, 6); } },
    { t: 0.3, b: 'lift', v: 'heldhigh', vp: { f: 0.6, y: 1.2, spd: 14 } },
    { t: 0.2, b: 'slam', v: 'facedown', vp: { f: 1.2, spd: 20 }, crack: 2 }],
    end: (c) => c.kill('crush') },
  { name: 'SPINE EXTRACTION', steps: [jab('punchL'), jab('punchR'),
    { t: 0.5, b: 'grab', v: 'choke', vp: { f: 0.75, y: 0.1 } },
    { t: 0.4, b: 'lift', v: P('choke', { hdx: -1 }), vp: { f: 0.75, y: 0.4 }, crack: 2 }],
    end: (c) => c.kill('spine') },
];

export const BEATS = [
  { name: 'CIVIC CORRECTION', steps: [jab('punchL'), jab('punchR'), jab('punchL'),
    { t: 0.45, b: 'uppercut', v: P('hurt', { hdx: -0.9, sp: -0.4 }), vp: { f: 1.2, y: 0.4 }, hit: 2, fx: (c) => c.g.teeth(c.head(), c.up, 6) }],
    end: (c) => c.beat() },
  { name: 'KNEECAP AUDIT', steps: [jab('punchL'),
    { t: 0.4, b: 'kick', v: P('hurt', { kr: -0.9 }), vp: { f: 1.3 }, crack: 1, fx: (c) => c.sfx('scream', { vol: 0.9 }) },
    { t: 0.4, b: P('kick', { ll: -1.6, lr: 0.3 }), v: P('kneel', { kl: -0.9 }), vp: { f: 1.3 }, crack: 1 }, jab('punchR', 'kneel')],
    end: (c) => c.beat({ kl: -1.1, kr: -0.8 }) },
  { name: 'ARM BAR OF THE LAW', steps: [jab('punchR'),
    { t: 0.4, b: 'grab', v: 'hurt', vp: { f: 0.9 } },
    { t: 0.4, b: 'twist', v: P('hurt', { ar: [-1.2, 1.5, 1.4], er: -1.3 }), vp: { f: 0.9 }, crack: 2, fx: (c) => c.sfx('scream', { vol: 1 }) }],
    end: (c) => c.beat({ ar: [-0.2, 1.5, -2.2], er: -1.4 }) },
  { name: 'GERMAN SUPLEX', steps: [jab('punchL'),
    { t: 0.4, b: 'grab', v: 'hurt', vp: { f: 0.6 } },
    { t: 0.4, b: 'lift', v: 'heldhigh', vp: { f: 0.1, y: 1.4 } },
    { t: 0.2, b: 'down', v: 'down', vp: { f: -1.4, y: 0, spd: 18 }, crack: 1, fx: (c) => { c.g.shockwave(c.n.pos, 4); c.shake(0.7); } }],
    end: (c) => { c.beat(); c.p.pos.addScaledVector(c.dir, -0.2); } },
  { name: 'FACE-FIRST FILING', steps: [jab('punchR'),
    { t: 0.4, b: 'grab', v: 'held', vp: { f: 0.8, y: 0.2 } },
    { t: 0.3, b: 'hammer', v: 'facedown', vp: { f: 1.2 }, crack: 1, fx: (c) => { c.g.pool(c.n.pos.x, c.n.pos.z, 1); c.g.teeth(c.head(), c.up, 4); } },
    { t: 0.3, b: 'stomp', v: 'facedown', vp: { f: 0.9 } },
    { t: 0.3, b: 'stompdown', v: 'facedown', vp: { f: 0.9 }, crack: 1 }],
    end: (c) => c.beat(POSES.facedown) },
  { name: 'DENTAL AUDIT', steps: [
    ...[0, 1, 2, 3, 4].map((i) => ({ t: 0.2, b: i % 2 ? 'punchR' : 'punchL', v: 'hurt', vp: { f: 1.1 }, hit: 1, fx: (c) => c.g.teeth(c.head(), c.dir, 2) }))],
    end: (c) => c.beat() },
  { name: 'HEADBUTT OF JUSTICE', steps: [
    { t: 0.4, b: 'grab', v: 'held', vp: { f: 0.7, y: 0.15 } },
    { t: 0.25, b: P('grab', { sp: 0.6, hdx: 0.5 }), v: P('held', { hdx: -0.8 }), vp: { f: 0.7, y: 0.15 }, hit: 2 },
    { t: 0.25, b: 'grab', v: 'held', vp: { f: 0.7, y: 0.15 } },
    { t: 0.3, b: P('grab', { sp: 0.6, hdx: 0.5 }), v: P('held', { hdx: -0.8 }), vp: { f: 0.7, y: 0.15 }, hit: 2 }],
    end: (c) => c.beat() },
  { name: 'THE LONG DROP', steps: [jab('punchL'),
    { t: 0.5, b: 'lift', v: 'held', vp: { f: 0.7, y: 1.4 } },
    { t: 0.6, b: 'throw', v: 'heldhigh', vp: { f: 5, y: 3, spd: 6 }, fx: (c) => c.sfx('scream', { vol: 1 }) },
    { t: 0.2, b: 'idle', v: 'down', vp: { f: 7, y: 0, spd: 14 }, crack: 2, fx: (c) => c.g.pool(c.n.pos.x, c.n.pos.z, 1.2) }],
    end: (c) => c.beat({ ll: 0.9, kr: -1 }) },
];

// weapon-specific finishers when an item is equipped
export const ITEM_KILLS = {
  mallet: { name: 'GAVEL OF JUDGMENT', steps: [
    { t: 0.4, b: 'slam', v: 'hurt', vp: { f: 1.3 } },
    { t: 0.2, b: 'hammer', v: 'kneel', vp: { f: 1.3 }, crack: 2, hit: 2 },
    { t: 0.45, b: 'slam', v: 'kneel', vp: { f: 1.3 } },
    { t: 0.2, b: 'hammer', v: 'kneel', vp: { f: 1.3 }, crack: 2 }], end: (c) => c.kill('crush') },
  chainsaw: { name: 'BAT-CHAINSAW DIVORCE', steps: [
    { t: 0.3, b: 'aim', v: 'hurt', vp: { f: 1.1 }, fx: (c) => c.sfx('scream', { vol: 1 }) },
    { t: 1.2, b: P('aim', { spy: 0.6 }), v: 'shock', vp: { f: 1.0 }, fx: (c) => { c.g.fountain(c.n.ch.spine, 1.2, 160, c.dir.clone().negate().setY(0.5)); } }],
    end: (c) => c.kill('halve') },
  shock: { name: 'OVERCLOCKED GAUNTLETS', steps: [
    { t: 0.3, b: 'punchR', v: 'hurt', vp: { f: 1.1 }, hit: 1 },
    { t: 1.2, b: 'grab', v: 'shock', vp: { f: 0.9, y: 0.3 }, fx: (c) => { c.g.arcs(c.n.ch, 1.2); c.charTo(1.1); } }],
    end: (c) => c.kill('explode') },
  freeze: { name: 'COLD SHOULDER', steps: [
    { t: 0.8, b: 'aim', v: 'frozen', vp: { f: 1.2 }, fx: (c) => c.tintTo('#bfe6ff', 0.6) },
    { t: 0.3, b: 'kick', v: 'frozen', vp: { f: 1.3 } }], end: (c) => c.kill('shatter') },
};
